#!/usr/bin/env bash
#install nginx web server and config it
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart

