#!/usr/bin/env bash
#install nginx web server and config it
sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo chown -R "$USER":"$USER" /etc/nginx/sites-enabled/default

# shellcheck disable=SC1004
sudo sed -i '/listen 80 default_server/a\
rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGU1wu4/ permanent;' /etc/nginx/sites-available/default

sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i '/^listen 80 default_server/a\
error_page 404 /404.html;' /etc/nginx/sites-available/default


sudo service nginx restart
