#!/usr/bin/env bash
#loops from 1 to 10 and on 4th iteration display bad luck and on 8th iteration display good luck

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ];
	then
		echo "bad luck"
	elif [ $i -eq 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
